### ISSUE TITLE
CraftTweaker integration issues

### ISSUE THREAD

**Issue by Froggy800** [Morpheus1101/Avaritia#100] opened 2018-04-26 13:20 UTC
I noticed that the Extreme crafting table and the Neutronium Compressor completely ignore the NBT tags put in the scripts. Using [this](https://pastebin.com/YydfYjwr) script I can put use any type of enchanted book (even ones with an empty tag, obtained with a _give_ command) to obtain glass and name tags.

I used .withTag and .onlyWithTag separately to ease the reading of the script, I already know that I should use both to make sure that both the recipe viewing via JEI and the crafting itself work as intended.

Tested with Avaritia 1.12 3.2.0.13, CodeChickenLib 1.12.2 3.1.6.339 and Forge 14.23.3.2670

**Comment by p455w0rd** [comment] 2018-07-04 20:35
#104 is technically a dupe of this (indirectly)...NBT was being taken into account for recipes and is now taen care of, thank you

**Closed by p455w0rd** 2018-07-04 20:35 UTC
