### ISSUE TITLE
[1.10.2] NeutroniumCompressor GUI dosent work on SMP

### ISSUE THREAD

**Issue by NoplixDE** [Morpheus1101/Avaritia#26] opened 2017-05-29 18:23 UTC
So I just right click it with an empty hand, but it doesn't work the GUI don't open and I get this error in the Server log ever time i tried to use Neutronium Compressor.
Everything works fine Singleplayer world.

Error: [Link](https://pastebin.com/raw/RawF1tQM)

**Comment by IDKZAL** [comment] 2017-05-29 18:26
Forgot to mention.
Everything is up to date. (Forge/Avaritia) 1.10.2

**Comment by TheSpamMiner** [comment] 2017-05-29 20:00
I got a similar crash, for the same thing. Mine had copper blocks being piped in via Ender IO item conduits and with a hopper underneath.
Here's the crash: https://pastebin.com/raw/wS0BasEU
If I should add a new issue instead, let me know.

**Comment by IDKZAL** [comment] 2017-06-01 15:50
I know asking this stuff is annoying but I would like to know when the fix will be out because I can't make any items as long as the Compressor doesn't work :/ And cheating is not cool in a survival world :3

**Comment by Morpheus1101** [comment] 2017-06-04 13:24
The compressor works for me on all items on a Dedicated server using EnderIO & Thermal conduits.  However the GUI dosent which will be fixed soonish

**Comment by Morpheus1101** [comment] 2017-06-11 11:49
Fixed but still an issue, but now slightly different output error code:

[21:33:33] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: morph.avaritia.tile.TileNeutroniumCompressor.getInputItems()Ljava/util/List;
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: morph.avaritia.tile.TileNeutroniumCompressor.getInputItems()Ljava/util/List;
        at morph.avaritia.container.ContainerNeutroniumCompressor.<init>(ContainerNeutroniumCompressor.java:25) ~[ContainerNeutroniumCompressor.class:?]
        at morph.avaritia.client.gui.GUIHandler.getServerGuiElement(GUIHandler.java:52) ~[GUIHandler.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
        at morph.avaritia.block.BlockNeutroniumCompressor.func_180639_a(BlockNeutroniumCompressor.java:71) ~[BlockNeutroniumCompressor.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NoSuchMethodError: morph.avaritia.tile.TileNeutroniumCompressor.getInputItems()Ljava/util/List;
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_131]
        at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:1.8.0_131]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:1.8.0_131]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:1.8.0_131]
        at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_131]
        at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_131]
        at morph.avaritia.container.ContainerNeutroniumCompressor.<init>(ContainerNeutroniumCompressor.java:25) ~[ContainerNeutroniumCompressor.class:?]
        at morph.avaritia.client.gui.GUIHandler.getServerGuiElement(GUIHandler.java:52) ~[GUIHandler.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
        at morph.avaritia.block.BlockNeutroniumCompressor.func_180639_a(BlockNeutroniumCompressor.java:71) ~[BlockNeutroniumCompressor.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more

**Closed** 2017-06-25 02:58 UTC
Labels: 1.10.2, bug, Confirmed
