### ISSUE TITLE
Client Crash by opening GUI Dire Table

### ISSUE THREAD

**Issue by Deloyar81** [Morpheus1101/Avaritia#15] opened 2017-05-06 14:52 UTC
**Issue Description:**

The Client crashes when I'm opening the GUI of the Dire Crafting Table.

**Steps to reproduce:**

Opening the GUI again

**Affected Versions:**

Avaritia: 1.10.2-2.1.0.1
Minecraft: 1.10.2
Forge: 12.18.3.2281

**Crash-Report:**

https://pastebin.com/fkwujXUa

**Comment by Morpheus1101** [comment] 2017-05-07 02:02
Could you remove the backpack mod and see if this issue still occurs please

**Comment by Deloyar81** [comment] 2017-05-07 09:43
The issue doesn't occur after removing the backpack mod.

Is this a problem you can help with on your side or should I go to the backpack issue tracker:
https://minecraft.curseforge.com/projects/forge-backpacks/issues

I like both mods and won't like to remove one of them.

**Comment by Morpheus1101** [comment] 2017-05-07 09:59
No afraid not, the issue is not on my end but with backpack mod, i suggest you report it on their tracker :)

**Comment by Deloyar81** [comment] 2017-05-07 11:31
It's me again. :)
Eydamos referenced it to you. ;)

https://minecraft.curseforge.com/projects/forge-backpacks/issues/30

**Comment by Morpheus1101** [comment] 2017-05-07 11:39
Would seem this is caused by table checking if a recipe has a result but instead directly tries to get the result out of the recipe.
https://minecraft.curseforge.com/projects/forge-backpacks/issues/30

**Comment by Morpheus1101** [comment] 2017-05-25 08:32
This should be fixed in current version just released, if it snot, feel free to re-open this issue

**Closed by Morpheus1101** 2017-05-25 08:32 UTC
Labels: bug

**Comment by covers1624** [comment] 2017-05-25 09:56
This is an issue with NoMoreRecipeConflict being fully retarded.

**Comment by Deloyar81** [comment] 2017-06-03 19:25
The issue already occurs, with the same crashlog.

**Affected Versions:**

Avaritia: 1.10.2-2.1.2.1
Backpack: 3.0.1-1.10.2
Minecraft: 1.10.2
Forge: 12.18.3.2297

**Comment by covers1624** [comment] 2017-06-03 22:25
The issue is with NoMoreRecipeConflict. You have that same mod, They are breaking our shit and we have nothing to do with this crash.
