### ISSUE TITLE
[1.10.2] Infinity Armor onarmor tick event causes crash

### ISSUE THREAD

**Issue by Morpheus1101** [Morpheus1101/Avaritia#12] opened 2017-04-23 05:09 UTC
(From User on Curse Page)

Upon taking damage with partial infinity armor, removed my boots to see how much damage I take and the game froze.

Crash Log @ https://gist.github.com/HellishINC/9d7b34bac2a1d75ebbe111a77a690dbd

**Comment by HellishINC** [comment] 2017-04-23 18:25
It should be noted that I could not reproduce this with minimal mods and no, it's not foamfix related. I'll do some further testing later today.

**Comment by HellishINC** [comment] 2017-04-24 03:21
(Not sure if github notifies you on edits so I went with a new message)

So it seems to crash when hit by some modded mobs. For example, The arachne mob from [Grimoire of Gaia 3](https://minecraft.curseforge.com/projects/grimoire-of-gaia?gameCategorySlug=mc-mods&projectID=228948) causes the crash reliably. I'm guessing this is because it applies a debuff on hit (Slowness, weakness and instant damage)?

**Comment by covers1624** [comment] 2017-04-24 03:22
I found the issue last night, fixed in dev.

**Comment by HellishINC** [comment] 2017-04-24 18:06
Damn. I hope it wasn't too hard to track down and knowing what caused it would have made things much easier. Comcast has been shit (down for ~18h) these past 2 days. Either way, thanks for your efforts.

**Comment by covers1624** [comment] 2017-04-25 02:04
Was really simple actually, first off the code was cancer so I rewrote it, then the issue was present, it was looping over all active potion effects on the player then removing bad ones, that causes concurrent modification exceptions as the removal removes from the list we are looping over, solution is to copy the list and do it that way.

**Comment by HellishINC** [comment] 2017-05-23 20:46
Is there a way to compile the dev build? There's no "Dev" branch on here.

**Comment by Morpheus1101** [comment] 2017-05-23 23:46
All dev work is kept locally, a new version will be pushed to curse in the next day or so, im currently awaiting a new motherboard.

**Comment by superon** [comment] 2017-06-06 17:22
"a new version will be pushed to curse in the next day or so"... did this happen? i can't find it, i'm experiencing this issue with chest transporters, obtain and natural pledge too.

**Comment by superon** [comment] 2017-06-06 17:29
i found this: https://minecraft.curseforge.com/projects/avaritia-1-10/files/2424947 which was posted at about the time specified but this version appears to have the issue persisting

**Comment by Morpheus1101** [comment] 2017-06-06 22:19
The issue had been fixed, but the same issue but different cause had appeared, hence why this was re-opened.  As yet there is no new release that has a fix for this.

**Closed** 2017-06-11 08:04 UTC
Labels: bug, Fixed in Dev
