### ISSUE TITLE
Crash / Character corruption when affected by continuously reapplied effects.

### ISSUE THREAD

**Issue by togreglove** [Morpheus1101/Avaritia#37] opened 2017-06-21 07:01 UTC
2 times now I have had my character unable to log on because I had the Infinity Chestplate on and got a continuous effect.  The first was when I picked up a spawner in a Diamond Chest Transporter and got the slowness and mining fatigue. The second was when I entered an RFTools dimension that gave me some status effect I was unable to determine. NBT editing out the Chestplate restored the ability to log on in both cases. 

Crash Report: https://pastebin.com/P2ub0FYg

Version 1.10.2

**Comment by Jo-Mamma75** [comment] 2017-06-21 08:38
So it appears that the issue that was supposed to be fixed in v2.2.4 still exists.

**Comment by Morpheus1101** [comment] 2017-06-21 08:45
Welp, that's another one to go back to the drawing board on.

**Comment by scalda** [comment] 2017-06-21 11:08
I am running the new version that you put out to fix the flight issue and I don't get the issue above.

regards

scalda
Iskall85 Community Administrator
FoolCraft DevTeam

**Comment by scalda** [comment] 2017-06-21 11:24
Hi sorry this needs reopening i just had the crash when using the chest transporter again sorry

**Comment by p455w0rd** [comment] 2017-06-21 18:38
@scalda when is the next foolcraft update planned? We had some issues that have been resolved now and I'd like to know how much time we have to get this update out...I have class soon so I won't be able to get back on this for ~6 hours

**Comment by scalda** [comment] 2017-06-22 09:07
I am waiting on avaritia to update to do the final release, so however long that will take really.

thanks for the hard work

**Comment by Morpheus1101** [comment] 2017-06-22 09:09
Hopefully it shouldn't take more than a day or 2 at this point, hopefully sooner.

**Comment by scalda** [comment] 2017-06-22 09:23
Ok sounds great, thanks

**Comment by p455w0rd** [comment] 2017-06-22 17:09
and thank you for working with us! you guys rock! I'm seriously doing my best to grind this out in the next 24 hrs

**Comment by Jo-Mamma75** [comment] 2017-06-22 18:44
Thanks again for all your hard work on this @p455w0rd

**Closed** 2017-06-24 22:01 UTC
Labels: 1.10.2, bug, Confirmed, Fixed in Dev

**Comment by scalda** [comment] 2017-06-25 00:21
I assume this has been fixed since the issue is closed? any idea on when the file will be available?

**Comment by Morpheus1101** [comment] 2017-06-25 02:53
Just testing 1 more thing and if its all good, then about 5-10minutes
