### ISSUE TITLE
Avaritia break flight with Angel Ring or Nano Bot Beacon /w Flight Core

### ISSUE THREAD

**Issue by NoplixDE** [Morpheus1101/Avaritia#35] opened 2017-06-14 12:06 UTC
Avaritia: 2.2.4
Forge: 12.18.3.2316
MC: 1.10.2

Idk how to show it but, i can try to explain it. 
The newest version of Avaritia breaks flight for some mods so I think it has to do something with creative fly itself that is used in some mods.
Everything works normally if I remove Avaritia, so it is a problem with the mod.
Angel Ring doesn't work and I tested the Nano Bot Beacon from Environmental Tech.
I don't get an error or anything. it just doesn't work. 
Just wanted to add in the Avaritia Version 2.1.2.1 flight works normally without any problems.
A hotfix would be cool because no flight is really annoying :/

**Comment by xAlicatt** [comment] 2017-06-15 01:50
Were you also suddenly unable to walk from dirt paths up onto stairs? Took me several hours to pinpoint Avaritia as the mod causing this problem for us, along with the flight issues. Creative flight with op worked fine for me, but Angel ring and spectator mode flight did not work at all. I switched into spectator on an OP'd/Perm'd account and still fell through the world.

**Comment by Lytearro** [comment] 2017-06-15 04:45
On https://github.com/Morpheus1101/Avaritia/blob/1.10.2-Full-Port/src/main/java/morph/avaritia/handler/AbilityHandler.java#L147

You can do a sort of work around with 
```java
                if (!player.capabilities.isCreativeMode && !player.capabilities.isSpectatorMode && player.capabilities.allowFlying) {
```
I cannot test this because I'm struggling to get the contents compiled, but this should be a fix for with other mods as well as server permissions given by donor ranks, etc.


The inability to walk from the dirt path to a block above it (ie. Stairs) is attributed by the Infinity Boots
https://github.com/Morpheus1101/Avaritia/blob/1.10.2-Full-Port/src/main/java/morph/avaritia/handler/AbilityHandler.java#L161
I cannot suggest a reliable fix that would work with other mods.

**Comment by APolarBaer** [comment] 2017-06-15 14:10
also breaks pretty much every other flying method, inventory pets cloud pet, silent gems flight rune for chaos gem, baubles stuff flight upgrade

**Comment by NoplixDE** [comment] 2017-06-15 18:30
A fast fix would be really cool, I mean we can't downgrade because of the problem with the Compressor and the newer version breaks every single flight ability... :/

**Comment by Morpheus1101** [comment] 2017-06-15 22:05
Some backend issues have arisen an once resolved i can push out a quick hot fix for this

**Comment by 47delasPECII** [comment] 2017-06-18 15:52
The supremium armor from mysticalagriculture won't wor either :(

**Comment by Lytearro** [comment] 2017-06-18 19:15
The fix I stated above in my first post should allow everything to work the way it's intended too as most mods do
```java
player.capabilities.allowFlying
```

**Comment by p455w0rd** [comment] 2017-06-19 20:17
I'll fix this..you guys are sort of on the right track..I think everyone who implements their first flight chestplate experiences this..I know I did..Brandon has a decent way of handling this in DE, I might just use that..what it boils down to is that their needs to be a registry of players within the mod itself that tell whether or not flight is enabled for this player

**Comment by fabri2000779** [comment] 2017-06-20 19:22
@p455w0rd hey man do you have a stimate time to fix this?

**Comment by Jo-Mamma75** [comment] 2017-06-21 08:41
I too would like an estimate on this for the purposes of our next update to FoolCraft.  Need to know if we should wait or revert to a previous version.  I would imagine that the general public, our Patrons and the Fools won't be too overly happy with non-existent creative flight capabilities.  Not trying to rush you.  Just wanted to get an idea so we can plan accordingly.
Thanks in advance.
Jo_Mamma75
Iskall85 Community Administrator
FoolCraft DevTeam

**Comment by Morpheus1101** [comment] 2017-06-21 08:47
With the various bugs that have been reported, i'll try an get a push for a new version done by end of the week.  The last few weeks or so, Ive been very flat out IRL and with comp troubles added onto it, things have piled up, my apologies to all.

**Comment by Morpheus1101** [comment] 2017-06-21 08:57
Fixed in https://github.com/Morpheus1101/Avaritia/commit/607c239882f242cb40c1d5385d48d05ef8cb91fd i hope

**Comment by Morpheus1101** [comment] 2017-06-21 09:57
v2.2.4.1 "should" solve this issue, but i shall leave it open untill its been confirmed fixed.

**Comment by scalda** [comment] 2017-06-21 11:06
Hi this is working great in the new version. i am testing it now in foolcraft 1.4.6.

Thanks for the hard work

Regards

Scalda
Iskall85 Community Administrator
FoolCraft DevTeam

**Closed** 2017-06-21 11:11 UTC
Labels: 1.10.2, bug, Fixed in Dev

**Comment by TheUnderTaker11** [comment] 2017-06-22 19:54
Um, I don't see how this would fix anything. You basically say, "If allowFlying=false, set allowFlying to false". Which in theory means as soon as you give people flight they will never lose it until something else removes it from them (Be it another mod or just logging out/back in).

What I found as the best way to do this is have a static ArrayList or Hashset that has the UUID of all players you enabled flight for(Meaning add them to the list in the same place you enable flight), and only ever disable flight if they are on that list, then remove them from the list right after disabling said flight.
