### ISSUE TITLE
[1.11.2] Move away from null ItemStack

### ISSUE THREAD

**Issue by ExpensiveKoala** [Morpheus1101/Avaritia#46] opened 2017-07-11 21:50 UTC
Use ItemStack.EMPTY instead. A lot of the code pertaining to Extreme crafting recipes use null ItemStacks.

**Comment by Morpheus1101** [comment] 2017-07-12 00:18
This is on the todo list, thanks for letting gus know though :D

**Comment by p455w0rd** [comment] 2017-07-26 17:56
I'm going to go ahead close this. The problem is fully resolved in dev and we'll be releasing our 1.11.2 port in the near future.

**Closed by p455w0rd** 2017-07-26 17:56 UTC
Labels: enhancement, Fixed in Dev
